### ISSUE TITLE
 Failed to change state for node: planner_server

### ISSUE THREAD

**Issue by Repp-cattt** [Adlink-ROS/neuronbot2#22]
Operating System:
ubuntu18.04
ROS2 Version:
eloquent
Steps to reproduce issue
1、Download the source code of the eloquent branch of neuronbot2
2、Build code
source /opt/ros/eloquent/setup.bash
colcon build
source ~/neuronbot2_ros2_ws/install/local_setup.bash
3、Bringup
ros2 launch neuronbot2_nav bringup_launch.py map:=/home/map/map.yaml open_rviz:=true
4、You will see the error messages as below: 
`[planner_server-5] [ERROR] []: Caught exception in callback for transition 10
[planner_server-5] [ERROR] []: Original error: According to the loaded plugin descriptions the class spatio_temporal_voxel_layer/SpatioTemporalVoxelLayer with base class type nav2_costmap_2d::Layer does not exist. Declared types are  nav2_costmap_2d::InflationLayer nav2_costmap_2d::ObstacleLayer nav2_costmap_2d::StaticLayer nav2_costmap_2d::VoxelLayer
[planner_server-5] [INFO] [global_costmap.global_costmap]: StaticLayer: Resizing costmap to 384 X 384 at 0.050000 m/pix
[planner_server-5] [WARN] []: Error occurred while doing error handling.
[planner_server-5] [FATAL] [planner_server]: Lifecycle node entered error state
[lifecycle_manager-9] [ERROR] [lifecycle_manager_navigation]: Failed to change state for node: planner_server`
How should I solve this problem?

**Comment by QQting** [comment]
Hi @Repp-cattt 
We've tested the eloquent-devel branch, and there are no errors when bringing up navigation.
If you are trying to use STVL, there is a demo branch tested with foxy: https://github.com/Adlink-ROS/neuronbot2/blob/z_demo-stvl-foxy/neuronbot2_nav/param/neuronbot_params.yaml 
Melodic is also available at https://github.com/Adlink-ROS/neuronbot2/tree/z_demo-stvl-melodic
Please take a look on the demo, thank you.

**Comment by Repp-cattt** [comment]
I downloaded these feature packs offline from github and compiled them successfully to rebuild the development environment for the eloquent version of ros2; both navigation2 and behavior tree v3 were built using source code; but running 'ros2 launch neuronbot2_nav navigation_launch.py use_sim_time:=true.&nbsp;
'There is still an error: "Failed to change state for node: planner_server".&nbsp;
Is there any solution?&nbsp;
At present, my environment only has the function packs of navigation2 and neuronbot2.





------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Ting ***@***.***&gt;; 
发送时间: 2021年3月30日(星期二) 下午2:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Adlink-ROS/neuronbot2]  Failed to change state for node: planner_server (#22)





 
Hi @Repp-cattt
 We've tested the eloquent-devel branch, and there are no errors when bringing up navigation.
 If you are trying to use STVL, there is a demo branch tested with foxy: https://github.com/Adlink-ROS/neuronbot2/blob/z_demo-stvl-foxy/neuronbot2_nav/param/neuronbot_params.yaml
 Melodic is also available at https://github.com/Adlink-ROS/neuronbot2/tree/z_demo-stvl-melodic
 Please take a look on the demo, thank you.

**Comment by QQting** [comment]
Can I ask why you are using the source build instead of binary build? Is it the network connection issue in China?

**Comment by Repp-cattt** [comment]
Yes, it is indeed.....（涙）
Now I have successfully opened the map, but there is no tf coordinate display, so I can't activate the lifecycle nodes,than I see a bunch of errors on startup about map or odom frame not existing..&nbsp;
By the way, is this code just a simulation?&nbsp;
Can it be run in an actual car?&nbsp;
My English is not very good. It's overturned by machine.





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Adlink-ROS/neuronbot2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月30日(星期二) 下午5:30
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Adlink-ROS/neuronbot2]  Failed to change state for node: planner_server (#22)





 
Can I ask why you are using the source build instead of binary build? Is it the network connection issue in China?

**Comment by QQting** [comment]
好，那你就講中文吧! 我還不知道對岸同胞也會打 (淚) 這種用法，以為只有台灣人會。

中國網路的問題，有看過人家建議改 DNS，請你試試看:
https://blog.csdn.net/weixin_39730025/article/details/113348458

這個程式的 neuronbot2_bringup 是控制我們實體 NeuronBot 的馬達和 LiDAR，而 neuronbot2_gazebo 則是控制模擬的馬達與 LiDAR. 如果你要跑在自己的車子上，neuronbot2_bringup 這一包就必須自行修改了。

**Comment by Repp-cattt** [comment]
首先非常感謝您的包容∠( ᐛ 」∠)＿
關於DNS的修改我已經做了嘗試。我現在想試著將你的代碼用在我自己的車子上；在此之前我想先把例程跑一遍，在運行
&nbsp;“# terminal 1
ros2 launch neuronbot2_nav localization_launch.py use_sim_time:=true # terminal 2 ros2 launch neuronbot2_nav navigation_launch.py use_sim_time:=true # terminal 3&nbsp;ros2 launch neuronbot2_nav rviz_view_launch.py use_sim_time:=true”&nbsp; &nbsp; 的時候我沒有在rviz中看到tf座標，無法指定2Dpose EStimate ，請問這個問題您有遇到過嗎？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Adlink-ROS/neuronbot2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月30日(星期二) 下午5:53
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Adlink-ROS/neuronbot2]  Failed to change state for node: planner_server (#22)





 
好，那你就講中文吧! 我還不知道對岸同胞也會打 (淚) 這種用法，以為只有台灣人會。
 
中國網路的問題，有看過人家建議改 DNS，請你試試看:
 https://blog.csdn.net/weixin_39730025/article/details/113348458
 
這個程式的 neuronbot2_bringup 是控制我們實體 NeuronBot 的馬達和 LiDAR，而 neuronbot2_gazebo 則是控制模擬的馬達與 LiDAR. 如果你要跑在自己的車子上，neuronbot2_bringup 這一包就必須自行修改了。

**Comment by QQting** [comment]
在跑 navigation 之前, 車子的馬達與 LiDAR 的驅動也要執行.
請問你有開另一個 terminal 執行` ros2 launch neuronbot2_gazebo neuronbot2_world.launch.py `了嗎？
有的話, 可以執行 `ros2 topic echo /odom` 以及` ros2 topic echo /tf `來檢查是否有收到訊息.

**Comment by QQting** [comment]
另外, 選用 Ubuntu 18.04 的考量是？ 有考慮過使用 Ubuntu 20.04 + ROS 2 Foxy 嗎?

**Comment by Repp-cattt** [comment]
&nbsp; &nbsp; 沒有另外再執行“ros2 launch neuronbot2_gazebo neuronbot2_world.launch.py”這個程序，只打開了三個terminal的時候/odom和/tf都沒有數據；現在執行了之後他們都有數據了！
不過這個是仿真的，如果我部署到我的車子上是否可以直接替換我的馬達與LiDAR的程序（重新更改話題）？另外，使用ubuntu18.04是因為我最近才開始用ros2，以前一直用的是ros1的ubuntu18.04-melodic版本，我怕ros2使用ubuntu20無法正常運行ros1_bridge。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Adlink-ROS/neuronbot2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月30日(星期二) 晚上6:21
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Adlink-ROS/neuronbot2]  Failed to change state for node: planner_server (#22)





 
在跑 navigation 之前, 車子的馬達與 LiDAR 的驅動也要執行.
 請問你有開另一個 terminal 執行ros2 launch neuronbot2_gazebo neuronbot2_world.launch.py了嗎？
 有的話, 可以執行 ros2 topic echo /odom 以及ros2 topic echo /tf來檢查是否有收到訊息.

**Comment by QQting** [comment]
佈署到你的車子要請你研究 neuronbot2_bringup 這包 package 裡面的程式和參數囉, 主要是馬達驅動程序和 LiDAR 程序要替換.
如果你的車子旋轉半徑, 馬達轉速等參數不同, neuronbot2_nav 裡面的 neuronbot_params.yaml 也要跟著改.

By the way, 如果覺得這個 repo 對你有幫助的話, 請幫忙按個 star 給個星星唷, 感謝!

**Comment by Repp-cattt** [comment]
好的，非常感謝您的回覆！我還想請教一個問題：neuronbot2_bringup這個包裡面的啟動程式裡有一段「if we use ekf」和「if we don’t use ekf」 ，ekf不是傳感器數據信息融合處理的嗎？這個難道不是必須的一步嗎？我不是很理解。如果不需要打開gazebo仿真的話，是使用bringup_launch.py文件提供馬達與LiDAR的數據嗎？(⊙v⊙)


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Adlink-ROS/neuronbot2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月30日(星期二) 晚上6:51
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Adlink-ROS/neuronbot2]  Failed to change state for node: planner_server (#22)





 
佈署到你的車子要請你研究 neuronbot2_bringup 這包 package 裡面的程式和參數囉, 主要是馬達驅動程序和 LiDAR 程序要替換.
 如果你的車子旋轉半徑, 馬達轉速等參數不同, neuronbot2_nav 裡面的 neuronbot_params.yaml 也要跟著改.
 
By the way, 如果覺得這個 repo 對你有幫助的話, 請幫忙按個 star 給個星星唷, 感謝!

**Comment by QQting** [comment]
是的, 對於移動精準度要求很高的車子, 可以用 IMU 來補足輪子移動或旋轉的誤差(尤其是旋轉). 對於精準度要求不高的車子, 融合 IMU 訊息就不是必要了, 只要輪子的里程計不要太差, 只靠輪子的里程計也足夠. 儘管輪子有累積誤差, 也可以在移動時依靠 LiDAR + AMCL演算法來修正誤差.

不開 gazebo 的話, 就要修改 neuronbot2_bringup bringup_launch.py 來呼叫你的底盤驅動、傳感器等。

**Comment by Repp-cattt** [comment]
我使用ros1_bridge 來傳輸我的底盤驅動與傳感器數據信息，在本地可以正常運行。但是當我使用ssh遠程登錄到車子上，使用rviz2卻又查看不到地圖；據說nav2有默認的rviz配置，是因為我rviz2沒有配置好嗎？


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Adlink-ROS/neuronbot2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月30日(星期二) 晚上9:09
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Adlink-ROS/neuronbot2]  Failed to change state for node: planner_server (#22)





 
是的, 對於移動精準度要求很高的車子, 可以用 IMU 來補足輪子移動或旋轉的誤差(尤其是旋轉). 對於精準度要求不高的車子, 融合 IMU 訊息就不是必要了, 只要輪子的里程計不要太差, 只靠輪子的里程計也足夠. 儘管輪子有累積誤差, 也可以在移動時依靠 LiDAR + AMCL演算法來修正誤差.
 
不開 gazebo 的話, 就要修改 neuronbot2_bringup bringup_launch.py 來呼叫你的底盤驅動、傳感器等。

**Comment by QQting** [comment]
請善用 ros2 topic 工具來檢查是否有收到訊息
ROS 2 DDS QoS 設定也有影響

**Comment by Repp-cattt** [comment]
在車子本地打開rviz2打算自己配置也是無法調出地圖，使用ros2 topic list 可以看到map話題；我好像沒有用到ROS 2 DDS QoS這個，會是它的問題嗎？




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Adlink-ROS/neuronbot2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月31日(星期三) 下午5:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Adlink-ROS/neuronbot2]  Failed to change state for node: planner_server (#22)





 
請善用 ros2 topic 工具來檢查是否有收到訊息
 ROS 2 DDS QoS 設定也有影響

**Comment by QQting** [comment]
rviz2 map 裡面的 Durability QoS 改一下試試

**Comment by Repp-cattt** [comment]
我將neuronbot2_nav裏的rviz2文件內容copy到rviz2默認的default.rviz文件中了，一開始直接打開rviz2是有地圖的，此時的Durability Policy是Volatile;當我嘗試更改成其他的選項時，地圖就不見了，此時復現了錯誤；當我把Durability Policy改為Volatile之後，地圖就沒辦法重現QAQ.....Durability Policy這個是實現什麽功能呀?


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Adlink-ROS/neuronbot2"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年3月31日(星期三) 下午5:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Adlink-ROS/neuronbot2]  Failed to change state for node: planner_server (#22)





 
rviz2 map 裡面的 Durability QoS 改一下試試
