### ISSUE TITLE
Waiting for subscriber to connect to /cmd_vel

### ISSUE THREAD

**Issue by ZhangQuan-hub** [Adlink-ROS/neuronbot2#29]
您好，當我按照步驟一步一步來時，啟動完gazebo地圖，用鍵盤控制小車運動，總是顯示Waiting for subscriber to connect to [/cmd_vel。然後我去查看topiclist，也沒有任何和/cmd_vel有關的話題。請問這個怎麼解決，謝謝您！]
![1679802225551](https://user-images.githubusercontent.com/95294457/227754343-5e5546ad-9ddd-409a-9c40-5151cef0a59b.jpg)

**Comment by QQting** [comment]
你好,
`roslaunch neuronbot2_gazebo neuronbot2_world.launch`
這個指令除了會把 gazebo 叫起來，也應該會把模擬的馬達控制下位機一併叫起，
請確認執行 gazebo 的 terminal 沒有任何 error.

**Comment by ZhangQuan-hub** [comment]
您好，我那幾天一直在嘗試著運行代碼，分別在兩個不同的ROS環境中，ros1的noetic以及ros2的galactic。

我發現在ros2中代碼沒有任何問題並且可以正常運行，而在ros1中不行，我反反複複檢查了很多次兩邊的代碼沒有什麼區別。而今天打開電腦莫名其妙在ros1中也運行出來了沒有錯誤。

順便提一下，我也嘗試了您的其他項目，BT_ros1以及BT_ros2。

您的項目對我目前的學習來說非常有用，特此感謝，祝您工作順利，生活愉快！

**Comment by QQting** [comment]
Hi @Mokkeey 

很開心有幫助到你, 也祝你一切順利~
